Громыко Артём Артурович Б9122-02.03.01сцт

In [397]:
import numpy as np

In [398]:
A_matrixes = [  # Тестовые матрицы
    np.array([
        [2.1, -4.5, -2.0], 
        [3.0, 2.5, 4.3], 
        [-6.0, 3.5, 2.5]
    ]), 
    np.array([
        [5, -1, 5], 
        [-3, 6, 2], 
        [10, -7, 0]
    ]), 
    np.array([
        [5, 2, 3], 
        [1, 6, 1], 
        [3, -4, -2]
    ]),  
    np.array([
        [1, 2, 1, 4], 
        [2, 0, 4, 3], 
        [4, 2, 2, 1], 
        [-3, 1, 3, 2]
    ]), 
    np.array([
        [2, 1, 3], 
        [11, 7, 5], 
        [9, 8, 4]
    ])
]

In [399]:
b_vectors = [  # Тестовые вектора
    np.array([19.07, 3.21, -18.25]), 
    np.array([3.2, 5.4, -1.2]), 
    np.array([3, 5, 8]), 
    np.array([13, 28, 20, 6]), 
    np.array([1, -6, -5]), 
]

In [400]:
x_vectors = [  # Точные решения для тестовых данных
    np.array([1.34025, -4.75798, 2.5771]), 
    np.array([0.7297, 1.2138, 0.1531]), 
    np.array([2, 1, -3]), 
    np.array([3, -1, 4, 2]), 
    np.array([-1, 0, 1]), 
]

In [401]:
def decompose_LU(A):
    """
    Функция, производящая LU разложение матрицы A
    """

    w, h = A.shape
    if w != h:
        raise ValueError("Матрица не квадратная")
    n = w

    L, U = np.zeros((n, n), float), np.zeros((n, n), float)

    # i = 0 Первая строка матрицы U
    for j in range(n):
        U[0, j] = A[0, j]

    # j = 0 Первый столбец матрицы L
    for i in range(n):
        L[i, 0] = A[i, 0] / U[0, 0]

    # i = j Диагональ матрицы L
    for index in range(n):
        L[index, index] = 1

    # Остальные эллементы матриц L и U
    for i in range(1, n):
        for j in range(1, n):
            if i <= j:
                U[i, j] = A[i, j]
                for k in range(i):
                    U[i, j] -= L[i, k] * U[k, j]

            else:
                L[i, j] = A[i, j]
                for k in range(j):
                    L[i, j] -= L[i, k] * U[k, j]
                L[i, j] /= U[j, j]

    return L, U

In [402]:
def solve(A, b, type):
    """
    Функция, решающая систему с треугольной матрицей
    """

    w, h = A.shape
    if w != h:
        raise ValueError("Матрица не квадратная")
    n = w

    X = [0 for _ in range(n)]

    if type == 'up':  # Верхняя треугольная 
        for j in range(n - 1, -1, -1):
            x = b[j]

            for i in range(n - 1, j, -1):
                x -= A[j, i] * X[i]

            x /= A[j, j]

            X[j] = x

    elif type == 'down':  # Нижняя треугольная
        for j in range(n):
            x = b[j]

            for i in range(j):
                x -= A[j, i] * X[i]

            x /= A[j, j]

            X[j] = x

    else:
        raise ValueError("type должен быть задан как \'up\' или \'down\'")
    
    return np.array(X)


In [403]:
def test(A, b, exact_x):
    L, U = decompose_LU(A)
    
    # print(f'{L=}')
    # print(f'{U=}')
    # print('\n')
    print(f'{A=}')
    print(f'LU={L @ U}')
    print('\n')

    y = solve(L, b, 'down')
    x = solve(U, y, 'up')

    print(f'{x=}')
    print(f'Точный x={exact_x}')

In [404]:
# Проверяем работоспособность алгоритма на тестовых данных
for index in range(5):  
    print(f'\n-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=   Тест №{index + 1}   =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-\n')
    test(A_matrixes[index], b_vectors[index], x_vectors[index])


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=   Тест №1   =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

A=array([[ 2.1, -4.5, -2. ],
       [ 3. ,  2.5,  4.3],
       [-6. ,  3.5,  2.5]])
LU=[[ 2.1 -4.5 -2. ]
 [ 3.   2.5  4.3]
 [-6.   3.5  2.5]]


x=array([ 1.34022645, -4.75800672,  2.57775289])
Точный x=[ 1.34025 -4.75798  2.5771 ]

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=   Тест №2   =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

A=array([[ 5, -1,  5],
       [-3,  6,  2],
       [10, -7,  0]])
LU=[[ 5. -1.  5.]
 [-3.  6.  2.]
 [10. -7.  0.]]


x=array([0.72965517, 1.2137931 , 0.15310345])
Точный x=[0.7297 1.2138 0.1531]

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=   Тест №3   =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

A=array([[ 5,  2,  3],
       [ 1,  6,  1],
       [ 3, -4, -2]])
LU=[[ 5.  2.  3.]
 [ 1.  6.  1.]
 [ 3. -4. -2.]]


x=array([ 2.,  1., -3.])
Точный x=[ 2  1 -3]

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=   Тест №4   =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

A=array([[ 1,  2,  1,  4],
 

In [405]:
# Решаем данные СЛАУ методом LU разложения
# СЛАУ I
L, U = decompose_LU(A=np.array([
    [13.14, -2.12, 1.17], 
    [-2.12, 6.3, -2.45], 
    [1.17, -2.45, 4.6]
]))

y = solve(L, np.array([1.27, 2.13, 3.14]), 'down')
x = solve(U, y, 'up')

print(f'Точное решение СЛАУ I - {x=}\n')

# СЛАУ II
L, U = decompose_LU(A=np.array([
    [4.31, 0.26, 0.61, 0.27], 
    [0.26 , 2.32, 0.18, 0.34], 
    [0.61, 0.18, 3.20, 0.31], 
    [0.27, 0.34, 0.31, 5.17]
]))

y = solve(L, np.array([1.02, 1.00, 1.34, 1.27]), 'down')
x = solve(U, y, 'up')

print(f'Точное решение СЛАУ II - {x=}\n')

Точное решение СЛАУ I - x=array([0.12996615, 0.80016894, 1.07572903])

Точное решение СЛАУ II - x=array([0.15331773, 0.35835406, 0.35066487, 0.19304791])

