Громыко Артём Артурович Б9122-02.03.01сцт

In [109]:
import numpy as np

In [110]:
A_matrixes = [  # Тестовые матрицы
    np.array([
        [81, -45, 45], 
        [-45, 50, -15], 
        [45, -15, 38]
    ]), 
    np.array([
        [6.25, -1, 0.5], 
        [-1, 5, 2.12], 
        [0.5, 2.21, 3.6]
    ]), 
    np.array([
        [1, 3, -2, 0, -2], 
        [3, 4, -5, 1, -3], 
        [-2, -5, 3, -2, 2], 
        [0, 1, -2, 5, 3], 
        [-2, -3, 2, 3, 4]
    ]),  
    np.array([
        [1, 2, 4], 
        [2, 13, 23], 
        [4, 23, 77]
    ])
]

In [111]:
b_vectors = [  # Тестовые вектора
    np.array([531, -460, 193]), 
    np.array([7.5, -8.68, -0.24]), 
    np.array([0.5, 5.4, 5.0, 7.5, 3.3]), 
    np.array([10, 50, 150]), 
]

In [112]:
x_vectors = [  # Точные решения для тестовых данных
    np.array([6, -5, -4]), 
    np.array([0.8, -2, 1]), 
    np.array([-6.0978, -2.2016, -6.8011, -8.8996, 0.1998]), 
    np.array([2.22, 0.55, 1.67]), 
]

In [113]:
def decompose_square_root(A):
    """
    Функция, производящая разложение методом квадратного корня
    """

    for val in np.linalg.eig(A)[0]:
        if val <= 0:
            print("Разложения не существует так как матрица не положительно определена")
            return None

    w, h = A.shape
    if w != h:
        raise ValueError("Матрица не квадратная")
    n = w

    W = np.zeros((n, n), float)

    # Разложение для первой строки
    W[0, 0] = np.sqrt(A[0, 0])
    for j in range(1, n):
        W[0, j] = A[0, j] / W[0, 0]

    # Разложение для всех остальных строк и столбцов
    for i in range(1, n):
        # Заполнение диагональных элементов
        W[i, i] = A[i, i]

        for k in range(i):
            W[i, i] -= W[k, i] ** 2
        W[i, i] = np.sqrt(W[i, i])
        
        # Заполнение элементов выше главной диагонали
        for j in range(i+1, n):
            W[i, j] = A[i, j]
            for k in range(i):
                W[i, j] -= W[k, i] * W[k, j]

            W[i, j] = W[i, j] / W[i, i]

    return W

In [114]:
def solve(A, b, type):
    """
    Функция, решающая систему с треугольной матрицей
    """

    w, h = A.shape
    if w != h:
        raise ValueError("Матрица не квадратная")
    n = w

    X = [0 for _ in range(n)]

    if type == 'up':  # Верхняя треугольная 
        for j in range(n - 1, -1, -1):
            x = b[j]

            for i in range(n - 1, j, -1):
                x -= A[j, i] * X[i]

            x /= A[j, j]

            X[j] = x

    elif type == 'down':  # Нижняя треугольная
        for j in range(n):
            x = b[j]

            for i in range(j):
                x -= A[j, i] * X[i]

            x /= A[j, j]

            X[j] = x

    else:
        raise ValueError("type должен быть задан как \'up\' или \'down\'")
    
    return np.array(X)


In [115]:
def test(A, b, exact_x):
    W = decompose_square_root(A)
    if W is None:
        return None
    
    # print(f'{W=}')
    # print('\n')

    print(f'{A=}')
    print(f'W^T*W={W.T @ W}')
    print('\n')

    y = solve(W.T, b, 'down')
    x = solve(W, y, 'up')

    # print(f'{b=}')
    # print(f'{y=}')
    print(f'{x=}')
    print(f'Точный x={exact_x}')

In [116]:
# Проверяем работоспособность алгоритма на тестовых данных
for index in range(4):  
    print(f'\n-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=   Тест №{index + 1}   =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-\n')
    test(A_matrixes[index], b_vectors[index], x_vectors[index])


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=   Тест №1   =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

A=array([[ 81, -45,  45],
       [-45,  50, -15],
       [ 45, -15,  38]])
W^T*W=[[ 81. -45.  45.]
 [-45.  50. -15.]
 [ 45. -15.  38.]]


x=array([ 6., -5., -4.])
Точный x=[ 6 -5 -4]

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=   Тест №2   =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

A=array([[ 6.25, -1.  ,  0.5 ],
       [-1.  ,  5.  ,  2.12],
       [ 0.5 ,  2.21,  3.6 ]])
W^T*W=[[ 6.25 -1.    0.5 ]
 [-1.    5.    2.12]
 [ 0.5   2.12  3.6 ]]


x=array([ 0.8, -2. ,  1. ])
Точный x=[ 0.8 -2.   1. ]

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=   Тест №3   =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Разложения не существует так как матрица не положительно определена

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=   Тест №4   =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

A=array([[ 1,  2,  4],
       [ 2, 13, 23],
       [ 4, 23, 77]])
W^T*W=[[ 1.  2.  4.]
 [ 2. 13. 23.]
 [ 4. 23. 77.]]


x=array([2.22222222, 0.555

In [117]:
# Решаем данные СЛАУ методом LU разложения
# СЛАУ I
W = decompose_square_root(A=np.array([
    [5.8, 0.3, -0.2], 
    [0.3, 4.0, -0.7], 
    [-0.2, -0.7, 6.7]
]))

y = solve(W.T, np.array([3.1, -1.7, 1.1]), 'down')
x = solve(W, y, 'up')

print(f'Точное решение СЛАУ I - {x=}\n')

# СЛАУ II
W = decompose_square_root(A=np.array([
    [4.12, 0.42, 1.34, 0.88], 
    [0.42, 3.95, 1.87, 0.43], 
    [1.34, 1.87, 3.20, 0.31], 
    [0.88, 0.43, 0.31, 5.17]
]))

y = solve(W.T, np.array([11.17, 0.115, 9.909, 9.349]), 'down')
x = solve(W, y, 'up')

print(f'Точное решение СЛАУ II - {x=}\n')

Точное решение СЛАУ I - x=array([ 0.56206926, -0.44359823,  0.13461121])

Точное решение СЛАУ II - x=array([ 1.45653917, -1.93309996,  3.46970779,  1.51312749])

